# Generated by Django 2.2.7 on 2020-07-16 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hangMansApp', '0002_game_letterknows'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='uui',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
