# Generated by Django 2.2.7 on 2020-07-16 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField(default=False, verbose_name='Win')),
                ('session', models.TextField(verbose_name='Session')),
                ('fault', models.IntegerField(default=0, verbose_name='Faults')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hangMansApp.Word', verbose_name='Word')),
            ],
        ),
    ]
