# Generated by Django 5.2.11 on 2026-02-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman', '0004_alter_game_id_alter_word_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hint'),
        ),
    ]
